re-work

diff --git a/md-exec b/md-exec
--- a/md-exec
+++ b/md-exec
@@ -1,6 +1,6 @@
 #!/bin/bash
-# remember to call "./addapps .getver" after version modifications!
-VERSION="1.0.2"
+# remember to update VERSION below after modifications!
+VERSION="1.1.0"
 
 
 show_help() {
@@ -38,7 +38,7 @@ show_help() {
   echo ""
 }
 
-declare -A opt_args
+opt_args=()
 opt_envsubst=0
 
 ####################################################################################
@@ -50,43 +50,12 @@ while [ "$#" -gt 0 ]; do
   case "$1" in
     -h|--help)      show_help        ; exit 0 ;;
     -v|--version)   echo "$VERSION"  ; exit 0 ;;
-    -o|--overwrite) opt_args+=($2)   ; shift  ;;
+    -o|--overwrite) opt_args+=("$2") ; shift 2 ;;
     -e|--envsubst)  opt_envsubst=1   ; shift  ;;
     *)   CURROPT="$CURROPT \"$1\"" ; shift 1 ;;
   esac
 done
 eval set -- $CURROPT
-
-function xxx()
-{
-options=$(getopt -l "help,version,overwrite" -o "hvoe:" -a -- "$@")
-eval set -- "$options"
-while true ; do
-  case "$1" in
-  -h|--help)
-    show_help
-    exit 0
-    ;;
-  -v|--version)
-    echo "$VERSION"
-    exit 0
-    ;;
-  -o|--overwrite)
-    opt_args+=($2)
-    ;;
-  -e)
-    opt_envsubst=1
-    shift
-    ;;
-  --)
-    shift
-    break;;
-  esac
-  shift
-done
-
-#echo "$@"
-}
 
 if [ "$1" = "" ] ; then
   show_help
@@ -100,11 +69,11 @@ fi
 
 FI="$1"
 if [ "$2" = "create" ] ; then
-  if [ -f $FI ] ; then
+  if [ -f "$FI" ] ; then
     echo "error: file already exist"
     exit 1
   fi
-  cat >$FI <<EOF
+  cat >"$FI" <<EOF
 # md-exec template
 
 [//]: # (md-exec: global)
@@ -144,6 +113,8 @@ if [ "$CMD" != "run" -a "$CMD" != "show" -a "$CMD" != "list" -a "$CMD" != "dump"
   exit 1
 fi
 TAG="$3"
+# escape regex metacharacters so the tag is matched literally in sed addresses
+TAG_RE=$(printf '%s' "$TAG" | sed 's/[][\\/.^$*]/\\&/g')
 
 script=$(mktemp)
 
@@ -158,30 +129,35 @@ RMC='/^[[:blank:]]*#/d;s/#.*//' # remove all comments
 ret=0
 if [ "$TAG" = "" ] ; then
   if [ "$CMD" = "show" ] ; then
-    cat $FI | sed $D2U | sed  -n '/```/,/```/p'                                | sed $EMPTY > $script
+    cat "$FI" | sed $D2U | sed  -n '/```/,/```/p'                                | sed $EMPTY > $script
   elif [ "$CMD" = "list" ] ; then
-    cat $FI | sed $D2U | grep "\`\`\`.*" | sed $RMT                            | sed $EMPTY > $script
+    cat "$FI" | sed $D2U | grep "\`\`\`.*" | sed $RMT                            | sed $EMPTY > $script
   else
-    cat $FI | sed $D2U | sed  -n '/```/,/```/p' | sed $RML                     | sed $EMPTY > $script
+    cat "$FI" | sed $D2U | sed  -n '/```/,/```/p' | sed $RML                     | sed $EMPTY > $script
   fi
 else
   if [ "$CMD" = "show" ] ; then
-    cat $FI | sed $D2U | sed  -n '/```global$\|```'$TAG'$/,/```/p'            | sed $EMPTY > $script
+    cat "$FI" | sed $D2U | sed  -n '/```global$\|```'$TAG_RE'$/,/```/p'            | sed $EMPTY > $script
   elif [ "$CMD" = "dump" ] ; then
-    cat $FI | sed $D2U | sed  -n '/```'$TAG'$/,/```/p' | sed $RML                          > $script
-  else 
-    cat $FI | sed $D2U | sed  -n '/```global$\|```'$TAG'$/,/```/p' | sed $RML | sed $EMPTY > $script
+    cat "$FI" | sed $D2U | sed  -n '/```'$TAG_RE'$/,/```/p' | sed $RML                          > $script
+  else
+    cat "$FI" | sed $D2U | sed  -n '/```global$\|```'$TAG_RE'$/,/```/p' | sed $RML | sed $EMPTY > $script
   fi
 fi
 
-for arg in "${!opt_args[@]}" ; do
-  var=${arg%=*}
+for arg in "${opt_args[@]}" ; do
+  var=${arg%%=*}
   val=${arg#*=}
-  sed -i "/^[[:blank:]]*${var}=*/c\\${var}=\"${val}\"" $script
+  sed -i "/^[[:blank:]]*${var}=/c\\${var}=\"${val}\"" $script
 done
 if [ "$CMD" = "list" -o "$CMD" = "show" -o "$CMD" = "dump" ] ; then
   if [ "$CMD" = "dump" -a "$opt_envsubst" = "1" ] ; then
-    export $(cat $FI | sed $D2U | sed  -n '/```'global'$/,/```/p' | sed $RML  | sed $EMPTY | sed $RMC | sed 's|"||g' | xargs -0)
+    if ! command -v envsubst >/dev/null 2>&1 ; then
+      echo "error: 'envsubst' not found (install the 'gettext' package)" >&2
+      rm $script
+      exit 1
+    fi
+    export $(cat "$FI" | sed $D2U | sed  -n '/```'global'$/,/```/p' | sed $RML  | sed $EMPTY | sed $RMC | sed 's|"||g' | xargs -0)
     cat $script | envsubst
   else
     cat $script
